<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBNkMjlH\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBNkMjlH/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBNkMjlH.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBNkMjlH\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBNkMjlH\App_KernelProdContainer([
    'container.build_hash' => 'BNkMjlH',
    'container.build_id' => 'e2312b23',
    'container.build_time' => 1597138320,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBNkMjlH');
