<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO6hLxF0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO6hLxF0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO6hLxF0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO6hLxF0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO6hLxF0\App_KernelDevDebugContainer([
    'container.build_hash' => 'O6hLxF0',
    'container.build_id' => '56233c3b',
    'container.build_time' => 1597234030,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO6hLxF0');
